config/routes.rb
Rails.application.routes.draw do
  mount GrapeSwaggerRails::Engine, at: "/docs/"
  mount ApplicationApi => "/"

  devise_for :employees, controllers: { registrations: 'registrations' }

  resources :groups do
    resources :contacts
  end
  resources :contacts, only: :[] do
    collection do
      get :all
    end
  end
  resource :employee, only: :show

  root 'groups#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :group

  validates :group_id, :name, presence: true
  validates :email, uniqueness: true
end

# == Schema Information
#
# Table name: contacts
#
#  id         :integer          not null, primary key
#  group_id   :integer
#  name       :string
#  email      :string
#  phone      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_contacts_on_group_id  (group_id)
#

app/models/employee.rb
class Employee < ApplicationRecord
  DOMAIN_NAME = 'inmar.com'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, dependent: :destroy

  validates :first_name, :last_name, :aadhar, presence: true
  validates :aadhar, uniqueness: true

  validate :password_complexity
  validate :email_domain

  before_save :ensure_authentication_token

  def ensure_authentication_token
    self.authentication_token ||= generate_authentication_token
  end

private
  def password_complexity
    # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a
    return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,70}$/

    errors.add :password, 'Complexity requirement not met. Length should be 8-70 characters and include: 1 uppercase, 1 lowercase, 1 digit and 1 special character'
  end

  def email_domain
    return if email.end_with?(DOMAIN_NAME)

    errors.add :email, "allowed form #{DOMAIN_NAME} only"
  end

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless Employee.where(authentication_token: token).first
    end
  end
end

# == Schema Information
#
# Table name: employees
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  first_name             :string
#  last_name              :string
#  aadhar                 :integer
#
# Indexes
#
#  index_employees_on_email                 (email) UNIQUE
#  index_employees_on_reset_password_token  (reset_password_token) UNIQUE
#

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :employee
  has_many :contacts, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

# == Schema Information
#
# Table name: groups
#
#  id          :integer          not null, primary key
#  employee_id :integer
#  name        :string
#  active      :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_groups_on_employee_id  (employee_id)
#  index_groups_on_name         (name)
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_employee!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_group, except: :all
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def all
    @contacts = Contact.joins(group: :employee).where("groups.employee_id = ?", current_employee.id)
  end

  # GET /groups/1/contacts
  # GET /groups/1/contacts.json
  def index
    @contacts = @group.contacts.all
  end

  # GET /groups/1/contacts/1
  # GET /groups/1/contacts/1.json
  def show
  end

  # GET /groups/1/contacts/new
  def new
    if !@group.active?
      redirect_back(fallback_location: groups_path, notice: 'Please enable the group')
    else      
      @contact = @group.contacts.new
    end
  end

  # GET /groups/1/contacts/1/edit
  def edit
  end

  # POST /groups/1/contacts
  # POST /groups/1/contacts.json
  def create
    @contact = @group.contacts.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to [@group, @contact], notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1/contacts/1
  # PATCH/PUT /groups/1/contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to [@group, @contact], notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1/contacts/1
  # DELETE /groups/1/contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to group_contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = current_employee.groups.find(params[:group_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = @group.contacts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :phone)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  # GET /employees/1
  # GET /employees/1.json
  def show
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = current_employee.groups.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = current_employee.groups.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = current_employee.groups.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = current_employee.groups.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :active)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


private
  def sign_up_params
    params.require(:employee).permit(:first_name, :last_name, :aadhar, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_link_class(link_controller)
    controller_name == link_controller ? 'active' : ''
  end
end

app/views/contacts/_form.html.haml
= form_for [@group, @contact] do |f|
  - if @contact.errors.any?
    #error_explanation
      %h2= "#{pluralize(@contact.errors.count, "error")} prohibited this contact from being saved:"
      %ul
        - @contact.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, class: 'required'
    = f.email_field :email, class: 'form-control'
  .form-group
    = f.label :phone, class: 'required'
    = f.number_field :phone, class: 'form-control'
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/contacts/_index.html.haml
%table.table.table-sm.table-hover.table-striped
  %thead
    %tr
      %th Group
      %th Name
      %th Email
      %th Phone
      %th Actions

  %tbody
    - @contacts.each do |contact|
      %tr
        %td= contact.group.name
        %td= contact.name
        %td= contact.email
        %td= contact.phone
        %td
          = link_to 'Show', [contact.group, contact]
          |
          = link_to 'Edit', edit_group_contact_path(contact.group, contact)
          |
          = link_to 'Destroy', [contact.group, contact], method: :delete, data: { confirm: 'Are you sure?' }

app/views/contacts/all.html.haml
%h1 Listing all contacts
= render 'index'

app/views/contacts/edit.html.haml
%h1 Editing contact

= render 'form'

= link_to 'Show', [@group, @contact]
\|
= link_to 'Back', group_contacts_path(@group)

app/views/contacts/index.html.haml
%h1 Listing contacts
= render 'index'
%br
= link_to 'New Contact', new_group_contact_path(@group)

app/views/contacts/new.html.haml
%h1 New contact

= render 'form'

= link_to 'Back', group_contacts_path(@group)

app/views/contacts/show.html.haml
%p#notice= notice

%p
  %b Group:
  = @contact.group.name
%p
  %b Name:
  = @contact.name
%p
  %b Email:
  = @contact.email
%p
  %b Phone:
  = @contact.phone

= link_to 'Edit', edit_group_contact_path(@group, @contact)
\|
= link_to 'Back', group_contacts_path(@group)

app/views/employees/show.html.haml
%p#notice= notice

%p
  %b Email:
  = current_employee.email
%p
  %b First Name
  = current_employee.first_name
%p
  %b Last Name
  = current_employee.last_name  
%p
  %b Mobile Number
  = current_employee.aadhar

= link_to 'Edit Details', edit_employee_registration_path

app/views/groups/_form.html.haml
= form_for @group do |f|
  - if @group.errors.any?
    #error_explanation
      %h2= "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
      %ul
        - @group.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :active
    = f.check_box :active
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/groups/edit.html.haml
%h1 Editing group

= render 'form'

= link_to 'Show', @group
\|
= link_to 'Back', groups_path

app/views/groups/index.html.haml
%h1 Listing groups

%table.table.table-sm.table-hover.table-striped
  %thead
    %tr
      %th Name
      %th Status
      %th Contacts Count
      %th Actions

  %tbody
    - @groups.each do |group|
      %tr
        %td= group.name
        %td= group.active ? 'Active' : 'Inactive'
        %td= group.contacts.count
        %td
          = link_to 'New Contact', new_group_contact_path(group)
          |
          = link_to 'Contacts', group_contacts_path(group)
          |
          = link_to 'Show', group
          |
          = link_to 'Edit', edit_group_path(group)
          |
          = link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Group', new_group_path

app/views/groups/new.html.haml
%h1 New group

= render 'form'

= link_to 'Back', groups_path

app/views/groups/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @group.name
%p
  %b Active:
  = @group.active

= link_to 'Edit', edit_group_path(@group)
\|
= link_to 'Back', groups_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title ContactManagementSystem
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand-sm.bg-dark.navbar-dark
      %a.navbar-brand{:href => "#"} Inmar
      %ul.navbar-nav
        %li.nav-item{class: active_link_class('employees')}
          = link_to 'My Profile', employee_path, class: 'nav-link'
        %li.nav-item{class: active_link_class('groups')}
          = link_to 'Groups', groups_path, class: 'nav-link'
        %li.nav-item{class: active_link_class('contacts')}
          = link_to 'Contacts', all_contacts_path, class: 'nav-link'
      %ul.nav.navbar-nav.ml-auto
        %li.nav-item
          %span.navbar-text
            = current_employee.email
            |
        %li.nav-item
          = link_to 'Sign out', destroy_employee_session_path, method: :delete, class: 'nav-link'

    .container-fluid
      %p.alert= alert
      = yield

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title ContactManagementSystem
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      .row
        .col-4
          %p.notice= notice
          %p.alert= alert
          = yield